const state={number:"",saved:JSON.parse(localStorage.getItem("callflow_saved")||"[]"),history:JSON.parse(localStorage.getItem("callflow_history")||"[]"),editing:null,callInterval:null,callSeconds:0};
const titles={home:["CALLING WORKSPACE","Good morning"],dialer:["DIALER","Dial a number"],saved:["SAVED NUMBERS","Your numbers"],history:["CALL HISTORY","Your calls"],billing:["BILLING","Balance & billing"],settings:["SETTINGS","Workspace settings"]};
const $=id=>document.getElementById(id); const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function persist(){localStorage.setItem("callflow_saved",JSON.stringify(state.saved));localStorage.setItem("callflow_history",JSON.stringify(state.history))}
function normalize(v){return String(v).replace(/[^0-9*#+]/g,"").slice(0,20)}
function pretty(v){if(!v)return"Enter a number";if(/[*#]/.test(v)||v.startsWith("+"))return v;let d=v.replace(/\D/g,"");if(d.length<=3)return d;if(d.length<=6)return `${d.slice(0,3)} ${d.slice(3)}`;if(d.length<=10)return `${d.slice(0,3)} ${d.slice(3,6)} ${d.slice(6)}`;return `${d.slice(0,3)} ${d.slice(3,6)} ${d.slice(6,10)} ${d.slice(10)}`}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2300)}
function updateDisplay(){$("numberDisplay").textContent=pretty(state.number);$("numberDisplay").classList.toggle("has-number",!!state.number);$("callButton").disabled=!state.number;$("clearNumber").disabled=!state.number}
function showPage(page){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active-page"));document.querySelectorAll(".nav-item").forEach(n=>n.classList.remove("active"));$(page).classList.add("active-page");document.querySelector(`[data-page="${page}"]`)?.classList.add("active");$("pageEyebrow").textContent=titles[page][0];$("pageTitle").textContent=titles[page][1];if(page==="saved")renderSaved();if(page==="history")renderHistory();if(page==="dialer")renderRecents();if(page==="home")renderHome();$("sidebar").classList.remove("open")}
function addDigit(k){if(state.number.length>=20)return;state.number+=k;updateDisplay()}
function renderSaved(filter=""){const list=$("savedList"),q=filter.toLowerCase();const rows=state.saved.filter(x=>(x.name+" "+x.number+" "+(x.note||"")).toLowerCase().includes(q));$("savedCount").textContent=state.saved.length;if(!rows.length){list.innerHTML=`<div class="empty-card"><div class="empty-icon">★</div><strong>${q?"No matching numbers":"No saved numbers"}</strong><span>${q?"Try another search.":"Save a number from the dialer and it will appear here."}</span></div>`;return}list.innerHTML=rows.map(x=>{const i=state.saved.indexOf(x);return `<div class="saved-row"><div class="saved-main"><div class="saved-avatar">${esc(x.name.slice(0,1).toUpperCase())}</div><div><div class="saved-name">${esc(x.name)}</div><div class="saved-number">${esc(pretty(x.number))}</div>${x.note?`<div class="saved-note">${esc(x.note)}</div>`:""}</div></div><div class="row-actions"><button class="secondary call-saved" data-number="${esc(x.number)}" data-name="${esc(x.name)}">☎ Call</button><button class="secondary edit-saved" data-index="${i}">Edit</button><button class="secondary delete-saved" data-index="${i}">Delete</button></div></div>`}).join("")}
function renderHistory(){const list=$("historyList");const h=state.history;$("historyCount").textContent=h.length;$("historyCompleted").textContent=h.filter(x=>x.status==="Completed").length;$("historyMissed").textContent=h.filter(x=>x.status==="Missed").length;$("historyDuration").textContent=formatTotal(h);if(!h.length){list.innerHTML=`<div class="history-empty empty-card"><div class="empty-icon">◷</div><strong>No call history</strong><span>Once you make calls, your activity will appear here.</span></div>`;return}list.innerHTML=h.map((x,i)=>`<div class="history-row"><div class="history-person"><div class="history-icon">${x.status==="Missed"?"↙":"↗"}</div><div><b>${esc(x.name||x.number)}</b><small>${esc(x.number)}</small></div></div><span>${esc(x.time)}</span><span>${esc(x.duration)}</span><span class="status ${x.status.toLowerCase()}">${esc(x.status)}</span><button class="secondary call-history" data-number="${esc(x.number)}" data-name="${esc(x.name||"")}">Call</button></div>`).join("")}
function formatTotal(h){let sec=h.reduce((a,x)=>a+(x.seconds||0),0);return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,"0")}`}
function renderRecents(){const html=state.history.slice(0,4).map(x=>`<button class="quick-action call-history" data-number="${esc(x.number)}" data-name="${esc(x.name||"")}"><span class="qa-icon">☎</span><span><b>${esc(x.name||x.number)}</b><small>${esc(x.number)} · ${esc(x.time)}</small></span><i>→</i></button>`).join("");$("dialerRecent").innerHTML=html||`<div class="empty-inline" style="height:130px"><span>◷</span><small>No recent calls</small></div>`}
function renderHome(){const h=state.history;const today=new Date().toDateString();$("todayCalls").textContent=h.filter(x=>new Date(x.ts).toDateString()===today).length;$("todaySub").textContent=h.length?"Activity recorded":"No calls yet";$("totalMinutes").textContent=formatTotal(h);$("savedCount").textContent=state.saved.length;const box=$("homeRecent");if(!h.length){box.innerHTML=`<div class="empty-card"><div class="empty-icon">◷</div><strong>No calls yet</strong><span>Your latest calling activity will appear here.</span></div>`;return}box.innerHTML=h.slice(0,4).map(x=>`<button class="quick-action call-history" data-number="${esc(x.number)}" data-name="${esc(x.name||"")}"><span class="qa-icon">☎</span><span><b>${esc(x.name||x.number)}</b><small>${esc(x.time)} · ${esc(x.duration)}</small></span><i>→</i></button>`).join("")}
function openSave(number=state.number,index=null){if(!number){toast("Enter a number first");return}state.editing=index;$("modalTitle").textContent=index===null?"Give this number a name":"Edit saved number";$("saveName").value=index===null?"":state.saved[index].name;$("savePhone").value=pretty(number);$("saveNote").value=index===null?"":state.saved[index].note||"";$('saveModal').classList.remove("hidden");setTimeout(()=>$("saveName").focus(),50)}
function closeSave(){$("saveModal").classList.add("hidden");state.editing=null}
function confirmSave(){const name=$("saveName").value.trim();const phone=normalize($("savePhone").value);const note=$("saveNote").value.trim();if(!name){toast("Add a name for this number");return}if(state.editing===null)state.saved.unshift({name,number:state.number,note,savedAt:Date.now()});else state.saved[state.editing]={...state.saved[state.editing],name,note};persist();closeSave();renderSaved();renderHome();toast(state.editing===null?"Number saved":"Number updated")}
function startCall(number=state.number,name=""){if(!number){toast("Enter a number first");return}number=normalize(number);state.number=number;updateDisplay();$("callingName").textContent=name||"Unknown number";$("callingNumber").textContent=pretty(number);$("callingAvatar").textContent=(name||number).slice(0,1).toUpperCase();$("callModal").classList.remove("hidden");state.callSeconds=0;$("callTimer").textContent="00:00";$("callState").innerHTML="<span></span> Connecting";clearInterval(state.callInterval);state.callInterval=setInterval(()=>{state.callSeconds++;$("callTimer").textContent=`${String(Math.floor(state.callSeconds/60)).padStart(2,"0")}:${String(state.callSeconds%60).padStart(2,"0")}`;if(state.callSeconds===2)$("callState").innerHTML="<span style='background:#12b76a'></span> Connected"},1000)}
function endCall(){clearInterval(state.callInterval);$("callModal").classList.add("hidden");const seconds=state.callSeconds;const h={name:$("callingName").textContent,number:state.number,duration:`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`,seconds,status:"Completed",time:new Date().toLocaleString([], {month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}),ts:Date.now()};state.history.unshift(h);persist();renderHome();renderHistory();renderRecents();toast("Call logged");state.callSeconds=0}
const settings={general:`<div class="setting-section"><h3>General</h3><p>Basic workspace preferences.</p><div class="setting-line"><div><b>Workspace name</b><small>Personal workspace</small></div><button class="secondary">Edit</button></div><div class="setting-line"><div><b>Desktop notifications</b><small>Show notifications for call events.</small></div><button class="toggle on"></button></div><div class="setting-line"><div><b>Compact mode</b><small>Use denser spacing throughout the workspace.</small></div><button class="toggle"></button></div></div>`,calling:`<div class="setting-section"><h3>Calling</h3><p>Calling behavior and provider settings.</p><div class="setting-line"><div><b>Provider</b><small>Not connected yet. This will be configured in the backend phase.</small></div><b style="color:#98a2b3">Not connected</b></div><div class="setting-line"><div><b>Default caller ID</b><small>Will use a provider number once connected.</small></div><button class="secondary">Configure</button></div><div class="setting-line"><div><b>Call recording</b><small>Reserved for the provider/backend phase.</small></div><button class="toggle"></button></div></div>`,account:`<div class="setting-section"><h3>Account</h3><p>Account and workspace controls.</p><div class="setting-line"><div><b>Account type</b><small>Personal workspace</small></div><b>Owner</b></div><div class="setting-line"><div><b>Session security</b><small>Authentication will be added during backend development.</small></div><button class="secondary">Configure</button></div></div>`,api:`<div class="setting-section"><h3>API Access</h3><p>Our public API will be added after the standalone calling product is complete.</p><div class="setting-line"><div><b>API status</b><small>CRM integration is intentionally not connected yet.</small></div><b style="color:#98a2b3">Coming later</b></div><div class="setting-line"><div><b>API keys</b><small>Keys will be created and revoked here.</small></div><button class="secondary">Manage later</button></div></div>`};
function initSettings(){document.querySelectorAll(".settings-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".settings-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("settingsContent").innerHTML=settings[b.dataset.settings]})});$("settingsContent").innerHTML=settings.general}

document.addEventListener("click",e=>{const nav=e.target.closest(".nav-item");if(nav)showPage(nav.dataset.page);const go=e.target.closest("[data-go]");if(go)showPage(go.dataset.go);const key=e.target.closest("[data-key]");if(key){addDigit(key.dataset.key);return}if(e.target.closest("#clearNumber")){state.number="";updateDisplay()}if(e.target.closest("#saveCurrent")){openSave()}if(e.target.closest("#pasteNumber")){navigator.clipboard?.readText().then(t=>{state.number=normalize(t);updateDisplay();toast(state.number?"Number pasted":"Clipboard has no usable number")}).catch(()=>toast("Paste permission unavailable"))}if(e.target.closest("#callButton"))startCall();if(e.target.closest("#closeModal")||e.target.closest("#cancelSave"))closeSave();if(e.target.closest("#confirmSave"))confirmSave();if(e.target.closest("#endCall"))endCall();const cs=e.target.closest(".call-saved,.call-history");if(cs)startCall(cs.dataset.number,cs.dataset.name);const del=e.target.closest(".delete-saved");if(del){state.saved.splice(+del.dataset.index,1);persist();renderSaved();renderHome();toast("Number deleted")}const edit=e.target.closest(".edit-saved");if(edit){const i=+edit.dataset.index;state.number=state.saved[i].number;updateDisplay();openSave(state.saved[i].number,i)}if(e.target.closest("#clearHistory")){if(state.history.length&&!confirm("Clear all call history?"))return;state.history=[];persist();renderHistory();renderHome();renderRecents();toast("Call history cleared")}if(e.target.closest("[data-action=save]")){showPage("dialer");setTimeout(()=>openSave(),100)}if(e.target.closest("#rechargeBtn"))toast("Recharge will be connected in the billing backend")});

document.addEventListener("keydown",e=>{if($("saveModal")&&!$("saveModal").classList.contains("hidden")&&e.key==="Escape")closeSave();if($("callModal")&&!$("callModal").classList.contains("hidden")&&e.key==="Escape")endCall();if(document.activeElement.tagName==="INPUT"||document.activeElement.tagName==="TEXTAREA")return;if(/^[0-9*#]$/.test(e.key))addDigit(e.key);if(e.key==="Backspace"){state.number=state.number.slice(0,-1);updateDisplay()}if(e.key==="Escape"){state.number="";updateDisplay()}if(e.key.toLowerCase()==="d")showPage("dialer")});
$("savedSearch").addEventListener("input",e=>renderSaved(e.target.value));$("mobileMenu").onclick=()=>$("sidebar").classList.toggle("open");
initSettings();renderHome();renderSaved();renderHistory();renderRecents();updateDisplay();
