const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY_SAVED="callflow_saved_v2", KEY_HISTORY="callflow_history_v2", KEY_SETTINGS="callflow_settings_v2";
let saved=JSON.parse(localStorage.getItem(KEY_SAVED)||"[]"), history=JSON.parse(localStorage.getItem(KEY_HISTORY)||"[]"), settings=JSON.parse(localStorage.getItem(KEY_SETTINGS)||'{"workspace":"CallFlow","country":"+234","confirmClear":true,"notifications":true}');
const save=()=>{localStorage.setItem(KEY_SAVED,JSON.stringify(saved));localStorage.setItem(KEY_HISTORY,JSON.stringify(history));};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function toast(msg,type=""){const e=document.createElement("div");e.className=`toast ${type}`;e.textContent=msg;$("#toast-root").append(e);setTimeout(()=>e.remove(),2500)}
function navigate(view){$$(".view").forEach(v=>v.classList.remove("active"));$(`#view-${view}`).classList.add("active");$$(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.view===view));const labels={home:"Home",dialer:"Dialer",saved:"Saved Numbers",history:"Call History",billing:"Billing",settings:"Settings"};$("#page-title").textContent=labels[view]||"CallFlow";$("#sidebar").classList.remove("open");renderAll();scrollTo(0,0)}
$$("[data-view]").forEach(b=>b.addEventListener("click",()=>navigate(b.dataset.view)));
$("#mobile-menu").onclick=()=>$("#sidebar").classList.toggle("open");
function normalize(n){return n.replace(/[^\d*+#]/g,"")}
function renderAll(){renderSaved();renderHistory();renderRecents();updateStats();loadSettings()}
function updateStats(){let completed=history.filter(x=>x.status==="completed"), mins=completed.reduce((a,x)=>a+(x.duration||0),0);$("#stat-calls").textContent=history.length;$("#stat-minutes").textContent=Math.round(mins/60)+"m";$("#stat-saved").textContent=saved.length;$("#history-total").textContent=history.length;$("#history-completed").textContent=completed.length;$("#history-minutes").textContent=Math.round(mins/60)+"m"}
function renderRecents(){let box=$("#dialer-recents");let arr=history.slice(0,5);box.innerHTML=arr.length?arr.map(x=>`<div class="compact-item"><div class="mini-avatar">${esc((x.name||x.number||"?").slice(0,1).toUpperCase())}</div><div class="item-main"><strong>${esc(x.name||"Unknown")}</strong><span>${esc(x.number)}</span></div><button class="round-call" data-redial="${esc(x.number)}">☎</button></div>`).join(""):`<div class="empty"><div class="empty-icon">◷</div><h3>No recent calls</h3><p>Your call history will appear here.</p></div>`}
function renderSaved(){let q=($("#saved-search")?.value||"").toLowerCase();let arr=saved.filter(x=>(x.name+" "+x.number+" "+(x.note||"")).toLowerCase().includes(q));$("#saved-list").innerHTML=arr.length?arr.map(x=>`<div class="saved-item"><div class="mini-avatar">${esc((x.name||"?").slice(0,1).toUpperCase())}</div><div class="item-main"><strong>${esc(x.name)}</strong><span>${esc(x.number)}</span>${x.note?`<span>${esc(x.note)}</span>`:""}</div><div class="item-actions"><button data-call="${esc(x.number)}">☎</button><button data-edit="${x.id}">Edit</button><button data-delete="${x.id}">Delete</button></div></div>`).join(""):`<div class="panel empty" style="grid-column:1/-1"><div class="empty-icon">☆</div><h3>${q?"No matches":"No saved numbers"}</h3><p>${q?"Try another search.":"Add your first number to make repeat calls faster."}</p></div>`}
function renderHistory(){$("#history-list").innerHTML=history.length?history.map(x=>`<div class="history-row"><span><strong>${esc(x.name||"Unknown")}</strong><br><small>${esc(x.number)}</small></span><span>${x.direction||"Outgoing"}</span><span>${new Date(x.started).toLocaleString()}</span><span>${formatDuration(x.duration||0)}</span><button data-redial="${esc(x.number)}">☎</button></div>`).join(""):`<div class="empty"><div class="empty-icon">◷</div><h3>No calls yet</h3><p>Calls will be logged here after the provider is connected.</p></div>`}
function formatDuration(s){if(!s)return "—";return `${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`}
function openModal(html){$("#modal-content").innerHTML=html;$("#modal-backdrop").classList.add("open")}
function closeModal(){$("#modal-backdrop").classList.remove("open")}
$("#modal-close").onclick=closeModal;$("#modal-backdrop").onclick=e=>{if(e.target.id==="modal-backdrop")closeModal()};
function addNumber(existing=null){openModal(`<h2>${existing?"Edit saved number":"Save number"}</h2><p>Keep the number available for one-tap calling.</p><div class="form-row"><label>Name</label><input id="m-name" value="${esc(existing?.name||"")}"></div><div class="form-row"><label>Phone number</label><input id="m-number" inputmode="tel" value="${esc(existing?.number||$("#number-input").value)}"></div><div class="form-row"><label>Note (optional)</label><textarea id="m-note" rows="3">${esc(existing?.note||"")}</textarea></div><div class="form-actions"><button class="secondary" id="m-cancel">Cancel</button><button class="primary" id="m-save">${existing?"Save changes":"Save number"}</button></div>`);
$("#m-cancel").onclick=closeModal;$("#m-save").onclick=()=>{let name=$("#m-name").value.trim(),number=normalize($("#m-number").value.trim()),note=$("#m-note").value.trim();if(!name||!number)return toast("Name and phone number are required","warn");if(existing){Object.assign(existing,{name,number,note})}else{saved.unshift({id:crypto.randomUUID(),name,number,note,created:Date.now()})}save();closeModal();renderAll();toast(existing?"Number updated":"Number saved","success")}}
$("#add-number-btn").onclick=()=>addNumber();
$("#save-from-dialer").onclick=()=>{if(!normalize($("#number-input").value))return toast("Enter a number first","warn");addNumber()};
$("#saved-search").oninput=renderSaved;
$("#clear-number").onclick=()=>{$("#number-input").value=""};
$("#backspace").onclick=()=>{$("#number-input").value=$("#number-input").value.slice(0,-1)};
$$(".dial-keypad button").forEach(b=>b.onclick=()=>{$("#number-input").value+=b.dataset.key;$("#number-input").focus()});
document.addEventListener("keydown",e=>{if(document.querySelector(".modal-backdrop.open"))return;if(/^[0-9*#]$/.test(e.key)){$("#number-input").value+=e.key;return}if(e.key==="Backspace"){$("#number-input").value=$("#number-input").value.slice(0,-1)}if(e.key==="Escape")$("#number-input").value=""});
function startDemoCall(number){number=normalize(number);if(!number)return toast("Enter a number first","warn");openModal(`<div style="text-align:center;padding:12px"><div class="phone-orb" style="margin:0 auto 18px;width:72px;height:72px;font-size:28px">☎</div><h2>Calling ${esc(number)}</h2><p>This is the frontend call state. The real provider will be connected in the backend phase.</p><div class="form-actions" style="justify-content:center"><button class="secondary" id="end-demo">End call</button></div></div>`);let started=Date.now();$("#end-demo").onclick=()=>{let duration=Math.floor((Date.now()-started)/1000);history.unshift({id:crypto.randomUUID(),number,direction:"Outgoing",status:"completed",started:new Date(started).toISOString(),duration});save();closeModal();renderAll();toast("Demo call logged","success")}}
$("#call-btn").onclick=()=>startDemoCall($("#number-input").value);
document.addEventListener("click",e=>{let b=e.target.closest("[data-redial]");if(b){$("#number-input").value=b.dataset.redial;navigate("dialer");return}b=e.target.closest("[data-call]");if(b){startDemoCall(b.dataset.call);return}b=e.target.closest("[data-edit]");if(b){let x=saved.find(a=>a.id===b.dataset.edit);if(x)addNumber(x);return}b=e.target.closest("[data-delete]");if(b){saved=saved.filter(x=>x.id!==b.dataset.delete);save();renderAll();toast("Number deleted")}})
$("#clear-history").onclick=()=>{if(!history.length)return;history=[];save();renderAll();toast("History cleared")};
$("#connect-provider").onclick=()=>toast("Provider connection belongs to the backend phase");
$("#api-info").onclick=()=>toast("API routes are placeholders until the backend is built");
$("#save-settings").onclick=()=>{settings.workspace=$("#workspace-name").value.trim()||"CallFlow";settings.country=$("#default-country").value.trim()||"+234";settings.confirmClear=$("#confirm-clear").checked;settings.notifications=$("#call-notifications").checked;localStorage.setItem(KEY_SETTINGS,JSON.stringify(settings));toast("Settings saved","success")};
function loadSettings(){if($("#workspace-name")){$("#workspace-name").value=settings.workspace;$("#default-country").value=settings.country;$("#confirm-clear").checked=settings.confirmClear;$("#call-notifications").checked=settings.notifications}}
$("#reset-data").onclick=()=>{if(confirm("Reset all locally stored CallFlow demo data?")){saved=[];history=[];save();renderAll();toast("Local data reset")}};
$("#global-search").onclick=()=>navigate("saved");$("#help-btn").onclick=()=>toast("CallFlow frontend preview — backend integration comes next");
renderAll();
